export const INIT_STATE = 'INIT_STATE'

export const GET_LIST_DATA_REQUEST = 'GET_LIST_DATA_REQUEST'

export const GET_LIST_DATA_SUCCESS = 'GET_LIST_DATA_SUCCESS'

export const GET_LIST_DATA_FAILURE = 'GET_LIST_DATA_FAILURE'

export const GET_LIST_DATA = 'GET_LIST_DATA'