export const INIT_STATE = 'INIT_STATE'

export const GET_LIST_DATA_REQUEST = 'GET_LIST_DATA_REQUEST'

export const GET_LIST_DATA_SUCCESS = 'GET_LIST_DATA_SUCCESS'

export const GET_LIST_DATA_FAILURE = 'GET_LIST_DATA_FAILURE'

export const GET_LIST_DATA = 'GET_LIST_DATA'

export const GET_FORM_CONFIG = 'GET_FORM_CONFIG'

export const GET_FORM_CONFIG_SUCCESS = 'GET_FORM_CONFIG_SUCCESS'

export const GET_FORM_CONFIG_FAILURE = 'GET_FORM_CONFIG_FAILURE'

export const SET_FORM_INITIAL_VALUES_FROM_DATA = 'SET_FORM_INITIAL_VALUES_FROM_DATA'

export const GET_SCHEDULED_EVENTS = 'GET_SCHEDULED_EVENTS'

export const GET_SCHEDULED_EVENTS_SUCCESS = 'GET_SCHEDULED_EVENTS_SUCCESS'

export const GET_SCHEDULED_EVENTS_FAILURE = 'GET_SCHEDULED_EVENTS_FAILURE'